CC		= g++

all:
	$(CC) -Wall -g DiceApp_100.cpp -o Dice100.out -lcurl
	$(CC) -Wall -g DiceApp.cpp -o DiceOne.out -lcurl

dice100:
	$(CC) -Wall -g DiceApp_100.cpp -o Dice100.out -lcurl

dice1:
	$(CC) -Wall -g DiceApp.cpp -o Dice1.out -lcurl
